server.port=8082
spring.application.name=ms-auditoria
spring.datasource.url=jdbc:mysql://localhost:3306/lextech_db?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
springdoc.swagger-ui.path=/swagger
springdoc.api-docs.path=/api-usu